### PR TITLE
Initial commit of LTE RDL

### PR DESCRIPTION
**Pull request by smooresni**

### CODE REVIEW

**Comment by smooresni** [comment]
@mdwhitten does this pull request still need review?

**Comment by mdwhitten** [comment]
@smooresni Yes, sorry I haven't come back to it yet. I'll try and approve it this week.

**Comment by smooresni** [comment]
> @smooresni VI Analyzer is reporting that the LTE Example is broken. I looked at it and I think you didn't update the example after changing the VI names. Could you update the example and push?
> Screen Shot 2019-07-24 at 12 07 14 PM

@mdwhitten fixed

**Comment by smooresni** [comment]
> ## LTE ACP Configuration.ctl
> Something is wrong with the _Averaging Type_ input below. I think it got copied and pasted from _Averaging Enabled_?
> 
> image

@mdwhitten not sure where this came from. Can you check again? Might have been bad linkages in the example. Should be okay now as I don't see this on my system anymore.

**Comment by smooresni** [comment]
> ## LTE Signal Config.vi
> 1. Can you elaborate on your decision to assume uplink?
> 2. How would supporting downlink change the function? Would it over-complicate the function?

@mdwhitten I added support for downlink test models

**Comment by smooresni** [comment]
> ## ModAcc Config/Fetch & ACP Config/Fetch
> 1. Thus far, all measurement modules have intentionally enabled _All Traces_ even if not used because it makes the process easier for a user to modify the fetch later. As in, a new user might try to fetch a constellation trace from the ModAcc measurement and not know where to go to enable the trace when the error occurs. I recognize this is a hit to performance.
> 2. You have added a _Measurement Enabled_ parameter to each of the measurement configurations rather than enabling by default. That's an interesting addition; can you elaborate on your thinking? That may be a valuable addition for other modules as well but I want to understand your thinking first. The thinking thus far is that each configure should intentionally enable the measurement for ease-of-use, and a user would later use _Select Measurements_ in order to specifically select other measurements. Do you see an advantage to your method here?
> 
> With either of these changes I want to make a decision as to whether other modules need to be changed so that the interfaces are consistent across modules.

1. Changed VIs to enable all traces by default
2. Encapsulation. Each configuration method is responsible for enabling or disabling the measurement. Nobody else is. Helps contain measurement configuration and properties to a single VI call for that measurement. I view as Measurement Enabled as a property of the measurement itself.

**Comment by mdwhitten** [comment]
FYI @smooresni in commit f46070ab3290fd2978ce44379be5e0e254611d32 I connected the selector string to this VI which was missing it. I assume this was an oversight, but let me know if there is some reason it ought not be connected.

image

**Comment by mdwhitten** [comment]
> > ## LTE ACP Configuration.ctl
> > Something is wrong with the _Averaging Type_ input below. I think it got copied and pasted from _Averaging Enabled_?
> > image
> 
> @mdwhitten not sure where this came from. Can you check again? Might have been bad linkages in the example. Should be okay now as I don't see this on my system anymore.

The issue was somehow the typedef visible on the front panel of _ACP Config.vi_ was out of step with the actual type def. I fixed it by making the type def strict, which forced an update on the front panel of the VI. I then reset the type def and saved the VI in commit c590387a11df1b63941b872193731e6d4876c22f

**Pull request merged**
