### PR TITLE
Load pull

### PR DESCRIPTION
**Pull request by Hanrock007**
**Why**
Azdo story: https://dev.azure.com/ni/DevCentral/_workitems/edit/976610
Adding LV RDL, example and Teststand sequence.

**How**
Create a new library for Focus tuner.
Add impedance sweep in example and sequence with TxP measurement.

**Test**
Ran the example and Teststand sequence and got the correct results.

### CODE REVIEW

**Comment by Hanrock007** [comment]
I have some cents on this one. The rest are resolved.
2. Connector panes needs to be changed to this one:
image

I feel most RDL blocks use 52225 pattern because RFmx/SG/SA and MI drivers use that pattern. But the Focus driver uses 4224 pattern. If RDL Focus Tuner block uses 52225, there would be a zigzag wire when mixing with RDL blocks and tuner driver calls. Initialize is an example.
image

Could we leave RDL blocks same pattern as the callee API?

@smooresni , @mdwhitten

**Comment by smooresni** [comment]
> I have some cents on this one. The rest are resolved.
> 2. Connector panes needs to be changed to this one:
> image
> 
> I feel most RDL blocks use 52225 pattern because RFmx/SG/SA and MI drivers use that pattern. But the Focus driver uses 4224 pattern. If RDL Focus Tuner block uses 52225, there would be a zigzag wire when mixing with RDL blocks and tuner driver calls. Initialize is an example.
> image
> 
> Could we leave RDL blocks same pattern as the callee API?
> 
> 1. Change label from "Config Common" to "Common Config". Helps identify it over the typedef.
>    image
> 
> What does this apply to? I updated the icon of Configure Common.vi. But I feel maybe I was wrong.
> image
> 
> @smooresni , @mdwhitten

Good point on the connector pane. I'd rather not have that zig-zag pattern. Lets keep the 4224 pattern.

That was right. Configure Common.vi was the one I was referring to.

**Comment by Hanrock007** [comment]
I was confused when comparing to RFmxDPD RDL. They are now having the same name "Configure Common.vi". But the icons are different now, after I modified the Focus one icon. That's why I feel I misunderstood the feedback.

image

@smooresni

**Comment by smooresni** [comment]
> I was confused when comparing to RFmxDPD RDL. They are now having the same name "Configure Common.vi". But the icons are different now, after I modified the Focus one icon. That's why I feel I misunderstood the feedback.
> 
> image
> 
> @smooresni

Ah yep good find. We should go back and fix the DPD one, but since it's cosmetic we can fix it here and change the DPD one later. I believe these VIs used to have a different name, hence the old icons are still lingering out there and we might have missed some.

**Comment by Hanrock007** [comment]
Thanks for the explanation. I will keep the new one.

**Pull request merged**
