### PR TITLE
DPD Conformity to C#

### PR DESCRIPTION
**Pull request by smooresni**
I stashed my changes from the #49 and applied them here.

### CODE REVIEW

**Comment by smooresni** [comment]
this pull request will fail until we merge latest sg code

**Comment by smooresni** [comment]
woohooo passing

**Comment by mdwhitten** [comment]
> 2. Configure Continuous Generation has a waveform in and a waveform out. The latter one is enriched with the generation script. It is tempting to use the output of Configure Continuous Generation for all subsequent VIs needing the waveform. If this output is wired to Perform Memory Polynomial then the Perform MP VI will change the waveform name but because it already has a script it will always write this reference waveform script instead of the postDPD script. So if you wire everything correctly it will work, otherwise DPD won't work at all and it is hard to find why this is happening. We could do a string search to catch that kind of issues: If the waveform name is included in the script we just apply the script, otherwise we run the Configure Continuous Generation again.

@smooresni This is a good point (and I think the same point must be made for C# as well). All of the work related to the scripts was predicated on the fact that the waveform name was not changing; i.e. we can only reuse the script if it references the same waveform. In your changes for C# and LabVIEW you have updated the waveform name, which introduces this new condition that you have to handle.

**Comment by manderseck** [comment]
> @smooresni This is a good point (and I think the same point must be made for C# as well). All of the work related to the scripts was predicated on the fact that the waveform name was not changing; i.e. we can only reuse the script if it references the same waveform. In your changes for C# and LabVIEW you have updated the waveform name, which introduces this new condition that you have to handle.
The advantage, however, of the changing waveform name is that in parameter sweeps we still have the original waveform in memory and can just switch back to it while with with an unchanged name we'd have to download the waveform again. So from that perspective I like this approach.

**Comment by smooresni** [comment]
> 1. Configure Common.vi doesn't have the correct waveform typedef.

Okay I'll fix that, thanks for finding.

>    _3. Perform Memory Polynomial doesn't have the Wait for Measurement Complete.vi included which was necessary for Teststand to run this VI correctly with several iterations. I still need to test if after the other changes in Perform Memory Polynomial it is still required._ => Tested, runs without Wait for Measurement Complete.

Any action required on this?

> 3. The Common Configuration holds the Enable/Disable for CFR again while the actual CFR parameter configuration is absent. Are you going to add the CFR configuration again? If not we should remove the enablers.

I'm going to remove it for this pull request. We decided to remove CFR from this PR and put it into a separate pull request once we validate dpd.

> 4. In the other branch (DPD-Dev) we handled the "Iterative DPD Enabled" flag differently. We removed it from the user config and set it automatically depending on the "Number of Iterations" value. What makes more sense from a user-perspective?

I like that better and will change it back.

**Comment by manderseck** [comment]
> Any action required on this?

Nope, that's fine.

**Comment by smooresni** [comment]
@manderseck @mdwhitten all feedback addressed in latest commits

**Comment by smooresni** [comment]
@mdwhitten changes ready for re-review/merge

**Comment by smooresni** [comment]
> Nice work!
> I already approved it because from looking at it everything was okay. Now when working with it I find two things:
> 
> 1. In Configure Common.vi the Common Configuration cluster has odd values for the synchronization mode (False/True instead of Direct/Alias Protected). Seems like LabVIEW got puzzled a little bit with the CFR toggles being removed from that cluster.
> 2. Perform Memory Polynomial now requires the Wait for Measurement Complete VI after the Initiate again, otherwise my Teststand will get stuck on the Perform VI until it reports that the VI execution was terminated by the server...

resolved in latest commits

**Comment by mdwhitten** [comment]
@smooresni Why did two SG VIs get updated in this code? Performing a diff shows nothing really changed - was it an accidental save/addition?

**Comment by smooresni** [comment]
> @smooresni Why did two SG VIs get updated in this pull request? Performing a diff shows nothing really changed - was it an accidental save/addition?

My commit notes for that say "Fix front panel controls and indicators all wonky". 
Hash ID: 47be1e41cf617061384ddc69cd4a0c7a96145622

Want to rebase and drop?

**Comment by mdwhitten** [comment]
> Want to rebase and drop?

I guess we don't have any active pull requests right now touching those files. As long as we don't I'm ok with you fixing them here.

**Comment by smooresni** [comment]
> * Reentrancy on VIs... could we set them back to non-reentrant for consistency?

Done

> * On both perform VIs, could we add some comments explaining about the "state caching" going on with RFSG? Adding a comment such as _Start generation if not currently_ and _Return generation to previous state_ or something like it would be sufficient

Done

> * Could you add a comment explaining the cumulative power offset calculated in Memory Polynomial?

You made me realize the implementation of this was incorrect. I've fixed it and will make an update to C#.

> * Is there a specific reason an In Place Element Structure is used for modifying the waveform properties in Memory Polynomial but not Lookup Table? Small thing but would ease customer understanding if there is not a difference

In place structure removed to make them more consistent.

> * _Perform & Configure Common_ in C# use an input named _ReferenceWaveform_. In LabVIEW it is just _Waveform_. Could we unify these?

Done. I changed the label in LabVIEW to "Reference Waveform"
> 
> I also fixed two instances where the types got messed up by doing the Strict Typdef and back method.

Thanks!

**Comment by smooresni** [comment]
> Everything looks good except for one tiny thing. Could you update the control on _Configure Common_ to have _Reference Waveform_ instead of just _Waveform_ to match C#?
> 

Done

> I'm not sure I understand the algorithm change for the power offsets. Please check with @heyItsDale if you want validation of the updated behavior. I noticed in the RFmx SpecAn examples that they just apply this offset to the PAPR. I assume we don't like affecting the PAPR in this way since it's no longer "true"?

@heyItsDale gave his stamp of approval. What you mentioned opens up a discussion on design decision. I'm not sure if we should be in the business of changing the rfsg average power.

**Pull request merged**
