### PR TITLE
Moved to DVR for waveform struct

### PR DESCRIPTION
**Pull request by mdwhitten**
Designed fix issues with passing large waveforms to/from TestStand

Additional changes:
- Waveform.ctl Element Name change: Waveform Data -> Data
- Waveform.ctl Element Name change: Waveform Name -> Name
- All VIs using type updated to use the new control

### CODE REVIEW

**Comment by mdwhitten** [comment]
I haven't updated the examples yet so the build will fail. But, I would like feedback on the approach.

**Comment by smooresni** [comment]
> * Read Waveform from Reference.vi is connected to the SG.lvlib but the library doesn't know that. Looks like this is what breaks the mass compile, too.

May I suggest a name change? That shares a similar name to Read Waveform from TDMS and thus implies much more is going on than a deference of a DVR. I think Get Waveform from Reference.vi or Dereference Waveform.vi are better.

**Comment by mdwhitten** [comment]
Thanks gentlemen! I just pushed a few changes. @manderseck, I needed to move things anyway into the common library so I decided to cherry-pick the commit from the LO sharing to add that to this pull request as well. That should also resolve the library issue. @smooresni, please check out the new names.

**Comment by manderseck** [comment]
I was way too quick with my positive feedback: The configure VIs are now faster but the VIs working with the waveforms are still just as long as they were without DVRs. Seems like unpacking the waveform from the DVR and working with that data is an issue, too.

**Comment by mdwhitten** [comment]
> Local Oscillator Sharing Mode: Make Automatic value 0 to match .net. Also so this is the "default"
Completed in commit 92e424cf228ec67fb434858b71b96ce83660ed17 in #55 

> Perform Lookup Table & Perform Memory Polynomial: Forgot some error wires
> Post our in person conversation:
> Move terminals for error wires in both reference and dereference functions.
> Name changes proposed: Get Waveform Data from Reference (or Dereference Waveform Data), New Waveform Data Reference

All others completed in latest commits

**Comment by manderseck** [comment]
Issues in Teststand were not related to the DVR, so no changes are required here anymore.

**Comment by smooresni** [comment]
> Issues in Teststand were not related to the DVR, so no changes are required here anymore.

@mdwhitten so should we go back to no DVR?

**Pull request merged**
